language: python

branches:
  # prevent bors temporary branches to be built
  except:
  - staging.tmp
  - trying.tmp

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - PKGS="python=3.7 flake8 black isort"  # Have linters fail first and quickly
  - PKGS="python=3.7 numpy pandas=0.24"
  - PKGS="python=3.7 numpy pandas=0.25.1"
  - PKGS="python=3.8 numpy pandas=0.24"
  - PKGS="python=3.8 numpy pandas=0.25.1"

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  # But broke travis 2019-08
  # - sudo rm -rf /dev/shm
  # - sudo ln -s /run/shm /dev/shm
  - export TEST_OPTS="-rfsxEX -s --cov=pint --cov-config=.coveragerc"

install:
  - conda create -n travis $PKGS pytest pytest-cov coveralls
  - source activate travis
  - if [[ $PKGS =~ flake8 ]]; then LINT=1; else LINT=0; fi
  - if [[ $PKGS =~ sphinx ]]; then DOCS=1; else DOCS=0; fi
  #  - if [[ $DOCS == 1 ]]; then pip install git+https://github.com/hgrecco/pint-pandas.git; fi
  # this is superslow but suck it up until updates to pandas are made
  # - if [[ $PANDAS == '1' ]]; then pip install numpy cython pytest pytest-cov nbval; pip install git+https://github.com/pandas-dev/pandas.git@bdb7a1603f1e0948ca0cab011987f616e7296167; python -c 'import pandas; print(pandas.__version__)'; fi
  - conda list

script:
  # if we're doing the pandas tests and hence have pytest available, we can
  # simply use it to run all the tests
  # - if [[ $PANDAS == '1' ]]; then python -bb -m coverage run -p --source=pint --omit="*test*","*compat*" -m py.test -rfsxEX; fi
  # test notebooks too if pandas available
  # - if [[ $PANDAS == '1' ]]; then pip install -e .; pytest --nbval notebooks/*; fi
  - if [[ $PANDAS == 0 && $LINT == 0 && $DOCS == 0 ]]; then python -bb -m pytest $TEST_OPTS; fi
  - if [[ $LINT == 1 ]]; then black -t py36 --check . && isort -rc -c . && flake8; fi
  - if [[ $LINT == 0 && $DOCS == 0 ]]; then coverage report -m; fi

after_success:
  - coveralls --verbose
