status = [
  "test (3.7, numpy>=1.14,<2.0.0, pandas==1.2)",
  "test (3.8, numpy>=1.14,<2.0.0, pandas==1.2)",
  "test (3.9, numpy>=1.14,<2.0.0, pandas==1.2)",
  "lint"
]
delete_merged_branches = true
timeout_sec = 10800
block_labels = [ "do-not-merge-yet" ]
